### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by andrewrosemberg** [GiacomoBastianel/PowerModelsTopologicalActions#3]
Besides deleting the files that are being tracked by git already that shouldn't (e.g., `.DS_Store`), it will be good to add them and others in `.gitignore`.

Here is an example of a few that are usually ignored:
```
.DS_Store
Manifest.toml
*.jl.cov
*.jl.*.cov
*.jl.mem
deps/deps.jl
docs/build/
docs/site/
docs/.documenter
.project
.tags
```

For a comprehensive example, have a look at a few packages that usually deal with a lot of auxiliary files in their pipeline:

[Powersimulations.jl](https://github.com/NREL-Sienna/PowerSimulations.jl/blob/main/.gitignore)

[UnitCommitment.jl](https://github.com/ANL-CEEESA/UnitCommitment.jl/blob/dev/.gitignore)

**Comment by andrewrosemberg** [comment]
you can ignore a whole folder as well, such as [.vscode](https://github.com/GiacomoBastianel/PowerModelsTopologicalActions.jl/tree/main/.vscode)

**Comment by GiacomoBastianel** [comment]
Updated .gitignore

**Comment by andrewrosemberg** [comment]
Perfect, just need to delete the files now so that they stop being tracked. The .gitigone will just prevent untracked files of being staged when you do `git add` in the future.
